config/routes.rb
Tournaments::Application.routes.draw do
  devise_for :users

  resources :u_groups

  resources :accounts

  resources :matches

  resources :games
  
  resources :tournaments
  root :to => 'page#index'

end

app/models/u_group.rb
class UGroup < ActiveRecord::Base
  has_many :users
end

app/controllers/u_groups_controller.rb
class UGroupsController < ApplicationController
  # GET /u_groups
  # GET /u_groups.json
  def index
    @u_groups = UGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @u_groups }
    end
  end

  # GET /u_groups/1
  # GET /u_groups/1.json
  def show
    @u_group = UGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @u_group }
    end
  end

  # GET /u_groups/new
  # GET /u_groups/new.json
  def new
    @u_group = UGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @u_group }
    end
  end

  # GET /u_groups/1/edit
  def edit
    @u_group = UGroup.find(params[:id])
  end

  # POST /u_groups
  # POST /u_groups.json
  def create
    @u_group = UGroup.new(params[:u_group])

    respond_to do |format|
      if @u_group.save
        format.html { redirect_to @u_group, notice: 'U group was successfully created.' }
        format.json { render json: @u_group, status: :created, location: @u_group }
      else
        format.html { render action: "new" }
        format.json { render json: @u_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /u_groups/1
  # PUT /u_groups/1.json
  def update
    @u_group = UGroup.find(params[:id])

    respond_to do |format|
      if @u_group.update_attributes(params[:u_group])
        format.html { redirect_to @u_group, notice: 'U group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @u_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /u_groups/1
  # DELETE /u_groups/1.json
  def destroy
    @u_group = UGroup.find(params[:id])
    @u_group.destroy

    respond_to do |format|
      format.html { redirect_to u_groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/u_groups_helper.rb
module UGroupsHelper
end

app/views/u_groups/_form.html.haml
= form_for @u_group do |f|
  -if @u_group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@u_group.errors.count, "error")} prohibited this u_group from being saved:"
      %ul
        - @u_group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/u_groups/edit.html.haml
%h1 Editing u_group

= render 'form'

= link_to 'Show', @u_group
\|
= link_to 'Back', u_groups_path

app/views/u_groups/index.html.haml
%h1 Listing u_groups

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @u_groups.each do |u_group|
    %tr
      %td= u_group.name
      %td= link_to 'Show', u_group
      %td= link_to 'Edit', edit_u_group_path(u_group)
      %td= link_to 'Destroy', u_group, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New U group', new_u_group_path

app/views/u_groups/new.html.haml
%h1 New u_group

= render 'form'

= link_to 'Back', u_groups_path

app/views/u_groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @u_group.name

= link_to 'Edit', edit_u_group_path(@u_group)
\|
= link_to 'Back', u_groups_path