config/routes.rb
Tournaments::Application.routes.draw do
  devise_for :users

  resources :u_groups

  resources :accounts

  resources :matches

  resources :games
  
  resources :tournaments
  root :to => 'page#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :tournament
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :ok }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.haml
= form_for @match do |f|
  -if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tournament_id
    = f.number_field :tournament_id
  .actions
    = f.submit 'Save'

app/views/matches/edit.html.haml
%h1 Editing match

= render 'form'

= link_to 'Show', @match
\|
= link_to 'Back', matches_path

app/views/matches/index.html.haml
%h1 Listing matches

%table
  %tr
    %th Tournament
    %th
    %th
    %th

  - @matches.each do |match|
    %tr
      %td= match.tournament_id
      %td= link_to 'Show', match
      %td= link_to 'Edit', edit_match_path(match)
      %td= link_to 'Destroy', match, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Match', new_match_path

app/views/matches/new.html.haml
%h1 New match

= render 'form'

= link_to 'Back', matches_path

app/views/matches/show.html.haml
%p#notice= notice

%p
  %b Tournament:
  = @match.tournament_id

= link_to 'Edit', edit_match_path(@match)
\|
= link_to 'Back', matches_path